from __future__ import annotations

from copy import deepcopy

import numpy as np
from sklearn.base import BaseEstimator, ClassifierMixin, RegressorMixin
from sklearn.utils.multiclass import unique_labels
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted

import statsmodels.api as sm


class SMWrapper(BaseEstimator):
    """Base class for scikit-learn wrappers around statsmodels models.

    Parameters
    ----------
    estimator : callable
        Statsmodels model class used to construct the model.
    fit_intercept : bool, default=True
        If True, add a constant to the exogenous variables before fitting
        and prediction.
    model_kwargs : dict, optional
        Keyword arguments passed to the statsmodels model constructor.
    fit_kwargs : dict, optional
        Keyword arguments passed to the statsmodels model fit method.

    Notes
    -----
    This class implements the common functionality used by SMRegressor and
    SMClassifier. It is not intended to be used directly when selecting an
    estimator for a scikit-learn workflow.
    """

    def __init__(
        self, estimator, fit_intercept=True, model_kwargs=None, fit_kwargs=None
    ):
        self.estimator = estimator
        self.fit_intercept = fit_intercept
        self.model_kwargs = model_kwargs
        self.fit_kwargs = fit_kwargs

    def _prepare_exog(self, X):
        X = check_array(X, ensure_2d=True, dtype="numeric")
        if self.fit_intercept:
            X = sm.add_constant(X, has_constant="skip")
        return X

    def _fit(self, X, y):
        X, y = check_X_y(X, y, ensure_2d=True, dtype=None)
        self.n_features_in_ = X.shape[1]
        X = self._prepare_exog(X)
        model_kwargs = (
            {} if self.model_kwargs is None else deepcopy(self.model_kwargs)
        )
        fit_kwargs = {} if self.fit_kwargs is None else deepcopy(self.fit_kwargs)
        self.model_ = self.estimator(endog=y, exog=X, **model_kwargs)
        self.results_ = self.model_.fit(**fit_kwargs)

    def predict(self, X):
        """Predict values using the fitted statsmodels results."""
        check_is_fitted(self, "results_")
        X = self._prepare_exog(X)
        return np.asarray(self.results_.predict(X))

    def summary(self, **summary_params):
        """Return the summary generated by the fitted statsmodels results.

        Parameters
        ----------
        **summary_params
            Keyword arguments passed to the statsmodels results summary
            method.

        Returns
        -------
        Summary
            The statsmodels summary object.
        """
        check_is_fitted(self, "results_")
        return self.results_.summary(**summary_params)


class SMRegressor(RegressorMixin, SMWrapper):
    """Wrap a statsmodels regression model for use with scikit-learn.

    Parameters
    ----------
    estimator : callable
        Statsmodels regression model class, such as statsmodels.api.OLS.
    fit_intercept : bool, default=True
        If True, add a constant to the exogenous variables before fitting
        and prediction.
    model_kwargs : dict, optional
        Keyword arguments passed to the statsmodels model constructor.
    fit_kwargs : dict, optional
        Keyword arguments passed to the statsmodels model fit method.

    Examples
    --------
    >>> import statsmodels.api as sm
    >>> from statsmodels.base.sklearn import SMRegressor
    >>> model = SMRegressor(sm.OLS)
    >>> model.fit([[1], [2], [3]], [2, 4, 6])
    SMRegressor(estimator=<class 'statsmodels.regression.linear_model.OLS'>)
    >>> model.predict([[4]])
    array([8.])
    """

    def __init__(
        self, estimator, fit_intercept=True, model_kwargs=None, fit_kwargs=None
    ):
        super().__init__(estimator, fit_intercept, model_kwargs, fit_kwargs)

    def fit(self, X, y):
        """Fit the statsmodels regression model.

        Parameters
        ----------
        X : array_like
            Training data with shape (n_samples, n_features).
        y : array_like
            Target values.

        Returns
        -------
        self
            Fitted estimator.
        """
        self._fit(X, y)
        return self


class SMClassifier(ClassifierMixin, SMWrapper):
    """Wrap a binary statsmodels model for use with scikit-learn.

    Parameters
    ----------
    estimator : callable
        Statsmodels classification model class, such as statsmodels.api.Logit.
    fit_intercept : bool, default=True
        If True, add a constant to the exogenous variables before fitting
        and prediction.
    model_kwargs : dict, optional
        Keyword arguments passed to the statsmodels model constructor.
    fit_kwargs : dict, optional
        Keyword arguments passed to the statsmodels model fit method.

    Notes
    -----
    The target can contain arbitrary binary labels. Labels are encoded to
    zero and one for statsmodels and decoded back to their original values
    by predict.
    """

    def __init__(
        self, estimator, fit_intercept=True, model_kwargs=None, fit_kwargs=None
    ):
        super().__init__(estimator, fit_intercept, model_kwargs, fit_kwargs)

    def fit(self, X, y):
        """Fit the statsmodels binary classification model.

        Parameters
        ----------
        X : array_like
            Training data with shape (n_samples, n_features).
        y : array_like
            Target values. Exactly two classes are required.

        Returns
        -------
        self
            Fitted estimator.
        """
        X, y = check_X_y(X, y, ensure_2d=True, dtype=None)
        self.classes_ = unique_labels(y)
        if self.classes_.size != 2:
            raise ValueError("SMClassifier only supports binary classification")
        y_encoded = (y == self.classes_[1]).astype(float)
        self._fit(X, y_encoded)
        return self

    def _predict_probability(self, X):
        X = self._prepare_exog(X)
        return np.asarray(self.results_.predict(X))

    def predict_proba(self, X):
        """Predict class probabilities.

        Parameters
        ----------
        X : array_like
            Samples for which to predict class probabilities.

        Returns
        -------
        proba : ndarray
            Class probabilities with columns ordered according to classes_.
        """
        check_is_fitted(self, ("results_", "classes_"))
        probabilities = self._predict_probability(X)
        if probabilities.ndim == 1:
            probabilities = np.column_stack((1 - probabilities, probabilities))
        if probabilities.ndim != 2 or probabilities.shape[1] != 2:
            raise ValueError("statsmodels model did not return two probabilities")
        return probabilities

    def predict(self, X):
        """Predict class labels.

        Parameters
        ----------
        X : array_like
            Samples for which to predict class labels.

        Returns
        -------
        y_pred : ndarray
            Predicted class labels.
        """
        probabilities = self.predict_proba(X)
        return self.classes_[np.argmax(probabilities, axis=1)]
